#!/usr/bin/env node
/* Builds supabase/functions/leaderboard/engine.js from the game's own files.

   The server has to replay a win with exactly the rules the browser played it
   by, so rather than keep a second copy of the chess engine it wraps the real
   ones: js/chess.js (the rules), js/leaderboard.js (name cleaning) and
   server/replay.js (the check). Run it after changing any of them, then deploy
   the function again. `node tools/build_function.js --check` only reports
   whether engine.js is up to date; the test suite uses that.            */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'supabase/functions/leaderboard/engine.js');
const SOURCES = ['js/chess.js', 'js/leaderboard.js', 'server/replay.js'];

function build() {
  const body = SOURCES.map((f) => `// ---- ${f} ----\n${fs.readFileSync(path.join(ROOT, f), 'utf8')}`).join('\n');
  return `// GENERATED by tools/build_function.js from ${SOURCES.join(', ')}. Do not edit by hand.\n` +
    `export default (function () {\n${body}\nreturn { replayWin, cleanName, encodeMove, LEVEL_NAMES };\n})();\n`;
}

const want = build();
if (process.argv.includes('--check')) {
  const have = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (have !== want) { console.error('engine.js is out of date: run node tools/build_function.js'); process.exit(1); }
  console.log('engine.js is up to date');
} else {
  fs.writeFileSync(OUT, want);
  console.log('wrote', path.relative(ROOT, OUT));
}
